server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/easy_task2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: postgres
    password: sangfor

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 日志级别
logging:
  level:
    root: INFO
    com.eztask: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Knife4j 配置
knife4j:
  enabled: true